name: Loanpartner
favicon: null
layout_spectrum: 0.9399316795170307
typography_spectrum: 0.991400248138234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09317156253382564
  lightness: 0.13085501454770565
  saturation: 0.14505838206969202
  rhythmicContrast: 0.288378658471629
purpose: []
