name: Loanpartner
favicon: null
layout_spectrum: 0.43179
typography_spectrum: 0.991400248138234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#372c57'
    - '#932f15'
    - '#797f43'
    - '#b1afba'
  brandStrength: 0.0625
  lightness: 0.13085501454770565
  saturation: 0.14505838206969202
  rhythmicContrast: 0.288378658471629
purpose: []
